### ISSUE TITLE
About the Sim-B/16*

### ISSUE THREAD

**Issue by renchao233** [LPXTT/SimTrack#14]
Hello, I would like to ask a question.   In this paper" Sim-B/16∗ denotes removing the last four layers of the transformerbackbone", can I understand that the original 12 floors have been reduced to 8 floors.Is that right?  Thank you!

**Comment by LPXTT** [comment]
Yes, that is right!

**Comment by renchao233** [comment]
> Yes, that is right!

Thank you for your reply! And thank you for working so efficiently.

**Comment by renchao233** [comment]
> > Yes, that is right!
> 
> Thank you for your reply! And thank you for working so efficiently.

Sorry， I have another question for you. After removing the 4 layers, do you still use the same method as importing the CLIP model, or do you rewrite the VIT framework? Because there are fewer resources in the group, I would like to use the work that requires less computation. Thank you for your reply.

**Comment by LPXTT** [comment]
Hi, as I remembered, I didn't rewrite the VIT framework.

**Comment by renchao233** [comment]
> Hi, as I remembered, I didn't rewrite the VIT framework.

Thank you for your reply！I will try this method in the future
