### ISSUE TITLE
Could you please share the models weight mentioned in the paper?

### ISSUE THREAD

**Issue by jananithangavel** [LPXTT/SimTrack#3]

**Comment by LPXTT** [comment]
Hi, I can share the model weights with you. But they are gotten from another training pipeline. You can not directly load the weights in the existing repository. You may need to change the name of some parameters. BTW, I haven't added the other model scripts in the repository. Please tell me which models you are interested in.  I can send both the network scripts and model weights to you. I may need more time to complete the repository. Sorry for that.

**Comment by LPXTT** [comment]
Hi, I can share the raw result of SimTrack-MAE (https://drive.google.com/file/d/1TPir2JSrWuV7ZEA92oV1vvjjXn0KCRrx/view?usp=sharing) in Table.5 (Succ-70.7, NormPre-80.0, Pre-75.6 on LaSOT dataset), which is based on a ViT-B/16 model and has similar results with Sim-L/14. It may take me some time to find the results of Sim-L/14. I will update them later. Hope the SimTrack-MAE result is useful for you!
