### ISSUE TITLE
Model release request

### ISSUE THREAD

**Issue by notnitsuj** [LPXTT/SimTrack#4]
Hi,

Can you release the weight of Sim-L/14 and its model architecture (modules and builder functions) needed for inference? I'm very impressed with the result and would like to try it in my project.

Thanks a lot.

**Comment by LPXTT** [comment]
Hi,
You can find them at https://drive.google.com/file/d/1dckYiNQn3fRMdvzVD4SPlxwkKGw5qKGY/view?usp=sharing. The file size is 3.5G. I am afraid that you may need to change some names while loading the weights. I am sorry I don't have time to change them for you recently.

**Comment by notnitsuj** [comment]
Thanks for sharing. I'll test it out.
