### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by jananithangavel** [LPXTT/SimTrack#5]
Could you provide your total training time ?

**Comment by LPXTT** [comment]
I use a server (a V100 with 8 GPUs ) to train the model. It takes 2 days to train SimTrack with VIT-b/16 and about 53 hr to train a SimTrack with VIT-L/14.

**Comment by LPXTT** [comment]
BTW, the training pipeline I used is similar to the pysot pipeline. I am not sure if the new pipeline will be faster or slower.

**Comment by vero1925** [comment]
> 
Is the code version released now(Sep 21st) the final Stark-based version?

**Comment by LPXTT** [comment]
I

> 



> > 
> 
> Is the code version released now(Sep 21st) the final Stark-based version?

Sorry. I am afraid I won't have enough time to release the new version before CVPR DDL.
