### ISSUE TITLE
Testing on the new dataset TNL2K

### ISSUE THREAD

**Issue by davidyang180** [LPXTT/SimTrack#7]
Hi! How did you test on the TNL2K dataset? I found that the official datasetloder file and python code have not been provided. Do you additionally train the model on the TNL2K training set and evaluate it?

**Comment by LPXTT** [comment]
Hi, I have the TNL2K testing script in another code pipeline. I am afraid I won't have enough time to implement it in the new pipeline before Dec 2022.  I will add the testing script for TNL2K as soon as possible when I have time. And the model is not additionally trained.  Thank you!
